name: ci-actions
on: [push]
jobs:
  install:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: c-hive/gha-yarn-cache@v2
      - uses: actions/cache@v2
        with:
          path: |
            ios/Pods
            example/ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - run: yarn install
  lint:
    runs-on: macos-11
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: c-hive/gha-yarn-cache@v2
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
      - run: yarn install
      - run: yarn lint
  test:
    runs-on: macos-11
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn
      - run: yarn test
  documentation:
    runs-on: macos-11
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn
      - run: yarn documentation
