name: ci-actions
on:
  push:
    branches:
      - "feature/*"
permissions:
  contents: write
jobs:
  documentation:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - uses: actions/cache@v3
        with:
          path:
            ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - uses: actions/cache@v3
        with:
          path:
            example/ios/Pods
          key: ${{ runner.os }}-example-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-example-pods-
      - run: yarn
      - run: yarn documentation
      - name: Ensure documentation is up to date
        run: ./scripts/ensureDocsAreUpdated.sh
